name: sbae-design
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyproj # Always include to avoid PROJ conflicts
  - numpy>=1.24.0
  - geopandas>=0.14.0
  - pandas>=2.0.0
  - shapely>=2.0.0
  - fiona>=1.8.0
  - scipy>=1.10.0
  - xarray>=2023.1.0
  - h5netcdf>=1.2.0
  - gdal
  - pip
  - rasterio
  - pip:
      - sepal_ui==3.1.0
      - git+https://github.com/openforis/earthengine-api.git@v1.6.14#egg=earthengine-api&subdirectory=python
      - ipecharts>=1.0.0
      - voila
